<template>
  <v-form>
    <v-container>
      <v-row>
        <v-col
          cols="0"
          sm="1"
          lg="2"
          xl="3"
        >
        </v-col>
        <v-col
          cols="12"
          sm="10"
          lg="8"
          xl="6"
        >
          <v-text-field
            variant="outlined"
            prepend-inner-icon="mdi-magnify"
            clearable
            label="Search for your game"
            placeholder="Which game do you want to search?"
          />
        </v-col>
        <v-col
          cols="0"
          sm="1"
          lg="2"
          xl="3"
        >
      </v-col>
      </v-row>
    </v-container>
  </v-form>
</template>
